[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3.11 -m pip install flask gspread oauth2client gunicorn --break-system-packages"
]

[start]
cmd = "python3.11 -m gunicorn --bind 0.0.0.0:$PORT app:app"
