[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.flask", "python311Packages.gunicorn"]

[phases.install]
cmds = ["pip install gspread oauth2client --break-system-packages"]

[start]
cmd = "python3 -m gunicorn --bind 0.0.0.0:$PORT app:app"
